# Generated by Django 4.0.2 on 2022-03-25 02:43

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reports', '0005_alter_problemreported_problem_id'),
        ('profiles', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profiles.profile')),
                ('liked', models.ManyToManyField(related_name='liked_prof', to='profiles.Profile')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(max_length=350)),
                ('image', models.ImageField(blank=True, upload_to=posts.models.get_upload_path, validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg'])])),
            ],
            bases=('posts.post',),
        ),
        migrations.CreateModel(
            name='ProblemPost',
            fields=[
                ('post_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='posts.post')),
                ('problem_reported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.problemreported')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reports.report')),
            ],
            bases=('posts.post',),
        ),
    ]
