# Generated by Django 4.0.2 on 2022-03-02 14:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
        ('areas', '0001_initial'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='report',
            name='production_line',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='areas.productionline'),
            preserve_default=False,
        ),
    ]
