# Generated by Django 4.0.2 on 2022-03-08 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_problemreported'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='problemreported',
            options={'verbose_name': 'Problem Reported', 'verbose_name_plural': 'Problems Reported'},
        ),
        migrations.AlterModelOptions(
            name='report',
            options={'ordering': ['-created']},
        ),
        migrations.AddField(
            model_name='problemreported',
            name='report',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reports.report'),
            preserve_default=False,
        ),
    ]
