# Generated by Django 4.0.2 on 2022-03-08 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
